name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract Git commit SHA
      - name: Extract Git commit SHA
        id: vars
        run: echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

      # Build the Docker image with both tags
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/py-docling-function:${{ env.COMMIT_SHA }} .
          docker tag ghcr.io/${{ github.repository_owner }}/py-docling-function:${{ env.COMMIT_SHA }} ghcr.io/${{ github.repository_owner }}/py-docling-function:latest

      # Push the Docker image with both tags
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/py-docling-function:${{ env.COMMIT_SHA }}
          docker push ghcr.io/${{ github.repository_owner }}/py-docling-function:latest
